// define action.type
export const GENERATE_SAMPLES = 'GENERATE_SAMPLES'
export type GENERATE_SAMPLES = typeof GENERATE_SAMPLES

export const FIND_GROUPS = 'FIND_GROUPS'
export type FIND_GROUPS = typeof FIND_GROUPS

export const CHANGE_SAMPLES_FETCH_STATUS = 'CHANGE_SAMPLES_FETCH_STATUS'
export type CHANGE_SAMPLES_FETCH_STATUS = typeof CHANGE_SAMPLES_FETCH_STATUS

export const CHANGE_GROUPS_FETCH_STATUS = 'CHANGE_GROUPS_FETCH_STATUS'
export type CHANGE_GROUPS_FETCH_STATUS = typeof CHANGE_GROUPS_FETCH_STATUS
