// define action.type
export const GENERATE_SAMPLES = 'GENERATE_SAMPLES'
export type GENERATE_SAMPLES = typeof GENERATE_SAMPLES

export const GENERATE_RULES = 'GENERATE_RULES'
export type GENERATE_RULES = typeof GENERATE_RULES

export const GENERATE_COMP_SAMPLES = 'GENERATE_COMP_SAMPLES'
export type GENERATE_COMP_SAMPLES = typeof GENERATE_COMP_SAMPLES

export const GENERATE_COMP_RULES = 'GENERATE_COMP_RULES'
export type GENERATE_COMP_RULES = typeof GENERATE_COMP_RULES

export const CHANGE_PROTECTED_ATTR = 'CHANGE_PROTECTED_ATTR'
export type CHANGE_PROTECTED_ATTR = typeof CHANGE_PROTECTED_ATTR

export const CHANGE_RULES_FETCH_STATUS = 'CHANGE_RULES_FETCH_STATUS'
export type CHANGE_RULES_FETCH_STATUS = typeof CHANGE_RULES_FETCH_STATUS

export const CHANGE_KEY_FETCH_STATUS = 'CHANGE_KEY_FETCH_STATUS'
export type CHANGE_KEY_FETCH_STATUS = typeof CHANGE_KEY_FETCH_STATUS

export const CHANGE_SAMPLES_FETCH_STATUS = 'CHANGE_SAMPLES_FETCH_STATUS'
export type CHANGE_SAMPLES_FETCH_STATUS = typeof CHANGE_SAMPLES_FETCH_STATUS

export const CHANGE_RULE_THRESHOLD = 'CHANGE_RULE_THRESHOLD'
export type CHANGE_RULE_THRESHOLD = typeof CHANGE_RULE_THRESHOLD

export const CHANGE_DRAG_ARRAY = 'CHANGE_DRAG_ARRAY'
export type CHANGE_DRAG_ARRAY = typeof CHANGE_DRAG_ARRAY

export const CHANGE_KEY_ATTR = "CHANGE_KEY_ATTR"
export type CHANGE_KEY_ATTR = typeof CHANGE_KEY_ATTR

export const CHANGE_SHOW_ATTRS = "CHANGE_SHOW_ATTRS"
export type CHANGE_SHOW_ATTRS = typeof CHANGE_SHOW_ATTRS

export const CHANGE_SHOW_DATASET = "CHANGE_SHOW_DATASET"
export type CHANGE_SHOW_DATASET = typeof CHANGE_SHOW_DATASET

export const CHANGE_XSCALE = "CHANGE_XSCALE"
export type CHANGE_XSCALE = typeof CHANGE_XSCALE

export const SELBAR = "SELBAR"
export type SELBAR = typeof SELBAR

export const FOLDFLAG = "FOLDFALG"
export type FOLDFLAG = typeof FOLDFLAG

export const ACCURACY = "ACCURACY"
export type ACCURACY = typeof ACCURACY